SELECT CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS 'Nome completo',
CONCAT(SUBSTRING(JH.START_DATE, 9, 2), SUBSTRING(JH.START_DATE, 5, 4), SUBSTRING(JH.START_DATE, 1, 4)) AS 'Data de início',
CONCAT(SUBSTRING(JH.END_DATE, 9, 2), SUBSTRING(JH.END_DATE, 5, 4), SUBSTRING(JH.END_DATE, 1, 4)) AS 'Data de rescisão',
YEAR(JH.END_DATE) - YEAR(JH.START_DATE) AS 'Anos trabalhados'
FROM hr.job_history AS JH
INNER JOIN hr.employees AS E
ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID
ORDER BY CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME), YEAR(JH.END_DATE) - YEAR(JH.START_DATE);
