SELECT DISTINCT CONCAT(UCASE(e.FIRST_NAME),' ', UCASE(e.LAST_NAME)) AS "Nome completo",
JH.START_DATE AS 'Data de início do cargo',
E.SALARY AS "Salário"
FROM hr.employees AS E
INNER JOIN hr.job_history AS JH ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID 
WHERE MONTH(JH.START_DATE) IN (1,2,3)
ORDER BY  CONCAT(UCASE(e.FIRST_NAME),' ', UCASE(e.LAST_NAME)) , JH.START_DATE;
