SELECT j.JOB_TITLE AS "Cargo",ROUND(AVG(e.SALARY), 2) AS "Média salarial",
CASE
WHEN AVG(SALARY) BETWEEN 2000 AND 5800 THEN "Júnior"
WHEN AVG(SALARY) BETWEEN 5801 AND 7500 THEN "Pleno"
WHEN AVG(SALARY) BETWEEN 7501 AND 10500 THEN "Sênior"
ELSE "CEO"
END AS "Senioridade"
/*referencia Felipe Alcantara*/
FROM hr.jobs AS j
INNER JOIN hr.employees AS e
ON e.JOB_ID = j.JOB_ID
GROUP BY j.JOB_ID
ORDER BY AVG(e.SALARY), Cargo;
