SELECT
CONCAT(UCASE(E.FIRST_NAME), ' ', UCASE(E.LAST_NAME)) 
AS 'Nome completo',
j.START_DATE AS 'Data de início',
E.SALARY AS 'Salário'
FROM hr.job_history AS j
INNER JOIN hr.employees AS E ON j.EMPLOYEE_ID = E.EMPLOYEE_ID AND
	MONTH(j.START_DATE) IN(1, 2, 3)
ORDER BY CONCAT(UCASE(E.FIRST_NAME), ' ', UCASE(E.LAST_NAME)), j.START_DATE;
