SELECT
PRODUCTS.ProductName AS 'Produto',
MIN(ORDER_DETAILS.QUANTITY) AS 'Mínima',
MAX(ORDER_DETAILS.QUANTITY) AS 'Máxima',
ROUND(AVG(ORDER_DETAILS.QUANTITY), 2) AS 'Média'
FROM
w3schools.products AS PRODUCTS
INNER JOIN
w3schools.order_details AS ORDER_DETAILS ON PRODUCTS.ProductID = ORDER_DETAILS.ProductID
GROUP BY `Produto`
HAVING `Média` > 20.00
ORDER BY `Média` ASC, `Produto` ASC;
