USE hr;
DELIMITER $$
CREATE PROCEDURE exibir_historico_completo_por_funcionario(IN email VARCHAR(100))
BEGIN
SELECT CONCAT(EMPLOYEES.FIRST_NAME, ' ', EMPLOYEES.LAST_NAME) AS 'Nome completo',
JOBS.JOB_TITLE AS 'Cargo',
DEPARTMENTS.DEPARTMENT_NAME AS 'Departamento'
FROM hr.job_history AS JOB_HIST
INNER JOIN hr.employees AS EMPLOYEES ON JOB_HIST.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID
INNER JOIN hr.jobs AS JOBS ON JOB_HIST.JOB_ID = JOBS.JOB_ID
INNER JOIN hr.departments AS DEPARTMENTS ON JOB_HIST.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
WHERE EMPLOYEES.EMAIL = email
ORDER BY `Departamento`, `Cargo`;
END $$
DELIMITER ;
