SELECT CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS 'Nome completo',
C.JOB_TITLE AS 'Cargo', 
S.START_DATE AS 'Data de início do cargo',
D.DEPARTMENT_NAME AS 'Departamento'
FROM hr.employees AS E
INNER JOIN hr.job_history AS S
ON E.EMPLOYEE_ID = S.EMPLOYEE_ID
INNER JOIN hr.jobs AS C
ON C.JOB_ID = S.JOB_ID
INNER JOIN hr.departments AS D
ON S.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) DESC, C.JOB_TITLE;
