-- SELECT
-- CONCAT(E.FIRST_NAME,' ',E.LAST_NAME) AS 'Nome completo',
-- CONCAT(IF(DAY(H.START_DATE)<10,CONCAT('0',DAY(H.START_DATE)),DAY(H.START_DATE)),'/',
-- IF(MONTH(H.START_DATE)<10,CONCAT('0',MONTH(H.START_DATE)),MONTH(H.START_DATE)),'/',
-- YEAR(H.START_DATE)) AS 'Data de início',
-- CONCAT(IF(DAY(H.END_DATE)<10,CONCAT('0',DAY(H.END_DATE)),DAY(H.END_DATE)),'/',
-- IF(MONTH(H.END_DATE)<10,CONCAT('0',MONTH(H.END_DATE)),MONTH(H.END_DATE)),'/',
-- YEAR(H.END_DATE)) AS 'Data de rescisão',
-- ROUND(DATEDIFF(H.END_DATE, H.START_DATE)/365,2) AS 'Anos trabalhados'
-- FROM hr.employees E
-- JOIN hr.job_history H ON H.EMPLOYEE_ID = E.EMPLOYEE_ID
-- ORDER BY CONCAT(E.FIRST_NAME,' ',E.LAST_NAME), DATEDIFF(H.END_DATE, H.START_DATE);
USE w3schools;
DELIMITER $$
CREATE TRIGGER set_order_date
    BEFORE INSERT ON orders
    FOR EACH ROW
BEGIN
    SET NEW.OrderDate = NOW();
END $$
DELIMITER ;
