SELECT 
CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME) AS 'Nome completo',
JBS.JOB_TITLE AS 'Cargo',
START_DATE AS 'Data de início do cargo',
DEP.DEPARTMENT_NAME AS 'Departamento'
FROM
  hr.job_history AS JB_H
INNER JOIN
  hr.jobs AS JBS
ON
  JB_H.JOB_ID = JBS.JOB_ID
INNER JOIN
  hr.employees AS EMP
ON
  JB_H.EMPLOYEE_ID = EMP.EMPLOYEE_ID
INNER JOIN
  hr.departments AS DEP
ON
  JB_H.DEPARTMENT_ID = DEP.DEPARTMENT_ID
ORDER BY
  CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME) DESC, JBS.JOB_TITLE ASC;
