SELECT 
  CONCAT(EMPLOYEES.FIRST_NAME, ' ', EMPLOYEES.LAST_NAME) AS 'Nome completo funcionário 1',
  EMPLOYEES.SALARY AS 'Salário funcionário 1',
  EMPLOYEES.PHONE_NUMBER AS 'Telefone funcionário 1',
  CONCAT(EMPLOYEES2.FIRST_NAME, ' ', EMPLOYEES2.LAST_NAME) AS 'Nome completo funcionário 2',
  EMPLOYEES2.SALARY AS 'Salário funcionário 2',
  EMPLOYEES2.PHONE_NUMBER AS 'Telefone funcionário 2'
FROM hr.employees AS EMPLOYEES, hr.employees AS EMPLOYEES2
WHERE EMPLOYEES.EMPLOYEE_ID <> EMPLOYEES2.EMPLOYEE_ID
AND EMPLOYEES.JOB_ID = EMPLOYEES2.JOB_ID
ORDER BY 1, 4;
