USE hr
DELIMITER $$
CREATE PROCEDURE buscar_media_por_cargo(IN JOB_TITLE VARCHAR(100))
BEGIN
    SELECT ROUND(AVG(E.SALARY), 2) AS 'Média salarial'
    FROM employees AS E
    INNER JOIN jobs AS J ON E.JOB_ID = J.JOB_ID
    WHERE E.JOB_TITLE = JOB_TITLE;
END $$
DELIMITER ;
