USE hr;
DELIMITER $$
CREATE PROCEDURE buscar_media_por_cargo(IN cargo VARCHAR(100))
BEGIN
SELECT ROUND(AVG(EMPLOYESS.SALARY), 2) AS 'Média salarial'
FROM hr.employees AS EMPLOYESS
INNER JOIN hr.jobs AS JOBS
ON EMPLOYESS.JOB_ID = JOBS.JOB_ID
WHERE JOBS.JOB_TITLE=cargo;
END $$
DELIMITER ;
