SELECT B.JOB_TITLE AS 'Cargo', ROUND(B.MIN_SALARY + B.MAX_SALARY/2, 2) AS 'Média salarial',
CASE
WHEN A.SALARY BETWEEN 2000 AND 5800 THEN 'Júnior'
WHEN A.SALARY BETWEEN 5801 AND 7500 THEN 'Pleno'
WHEN A.SALARY BETWEEN 7501 AND 10500 THEN 'Sênior'
ELSE 'CEO'
END AS 'Senioridade'
FROM hr.employees AS A
INNER JOIN hr.jobs AS B
INNER JOIN hr.job_history AS C
ON A.JOB_ID = B.JOB_ID 
WHERE C.END_DATE = '0000-00-00'
ORDER BY ROUND(B.MIN_SALARY + B.MAX_SALARY/2, 2) ASC, B.JOB_TITLE;