USE hr
DELIMITER $$
CREATE FUNCTION buscar_quantidade_de_empregos_por_funcionario(EMAIL VARCHAR(50))
RETURNS INT READS SQL DATA
BEGIN
    DECLARE JOBS_IN_HISTORY INT;
    SELECT COUNT(JH.EMPLOYEE_ID) FROM job_history AS JH
    INNER JOIN employees AS E ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID
    WHERE EMAIL LIKE E.EMAIL
    INTO JOBS_IN_HISTORY;
    RETURN JOBS_IN_HISTORY;
END $$
DELIMITER ;
